# fly.toml app configuration file generated for budgetbuddy on 2024-11-04T12:20:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'budgetbuddy'
primary_region = 'cdg'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
